version: 2
updates:
  # yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
